name: Build

on:
  push:
    branches:
      - master
      - wip
      - improvement/*
      - feature/*
      - fix/*
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        compiler: [g++, clang++, cl]
        exclude:
          - os: macos
            compiler: g++
          - os: macos
            compiler: cl
          - os: ubuntu
            compiler: cl
    name: ${{matrix.os}} / ${{matrix.compiler}}
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{github.workflow}}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: cmake -S . -B build -DLIBUNICODE_TESTING=ON -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4

      - name: test
        run: ctest --test-dir build/src/unicode --build-config Debug
