name: Checks

on:
  push:
    paths-ignore:
    - '.github/ISSUE_TEMPLATE/**'
    - '.github/*.yml'
    - 'LICENSE.txt'
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_PR_TODOs:
    name: "Check PR-TODOs"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: "Checking for open PR-related TODO items"
      run: |
        set -ex
        ./scripts/check-pr-todos.sh

  check_clang_format:
    name: "Check C++ style"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install clang
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        sudo apt-get install clang-format-18
    - name: "Clang-format"
      run: find ./src/ -name "*.cpp" -o -name "*.h" | xargs clang-format-18 --Werror --dry-run
